fixed bin/test

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -4,9 +4,14 @@ REALPATH=$(which realpath || which readlink)
 REALPATH=$([[ "$REALPATH" =~ 'readlink' ]] && echo "$REALPATH -e" || echo "$REALPATH")
 DIR=$(dirname $($REALPATH ${BASH_SOURCE[0]}))
 ROOT=$($REALPATH $DIR/..)
+BASE=$($REALPATH $DIR/../../../..)
 EHIGH="\033[49;1;32m"
 EERROR="\033[49;1;31m"
 EEND="\033[00m"
+
+if [ ! -d "$BASE/vendor" ]; then
+  BASE=$ROOT
+fi
 
 echo "Testing application"
 cd $ROOT
@@ -15,7 +20,7 @@ GITFILES=$(git diff --cached --name-only --diff-filter=AM|xargs)
 PHPFILES=$(git diff --cached --name-only --diff-filter=AM|grep "\.php"|xargs)
 if [[ ! $GITFILES =~ "composer.lock" ]]
 then
-	echo -e "Do not forget to$EERROR update composer.lock$EEND"
+  echo -e "Do not forget to$EERROR update composer.lock$EEND"
 fi
 
 if [ -n "$PHPFILES" ]
@@ -26,6 +31,6 @@ else
     PHPFILES="src/"
     echo "Checking $PHPFILES"
 fi
-$ROOT/vendor/bin/phpcs --standard=psr2 $PHPFILES || exit 1
-$ROOT/vendor/bin/phpmd $ROOT/src text phpmd.rules.xml || exit 1
-$ROOT/vendor/bin/phpunit || exit 1
+$BASE/vendor/bin/phpcs --standard=psr2 $PHPFILES || exit 1
+$BASE/vendor/bin/phpmd $ROOT/src text phpmd.rules.xml || exit 1
+$BASE/vendor/bin/phpunit || exit 1
